[package]
name = "genjin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.37.0", features = ["ttf", "image", "gfx"] }
specs = "0.20.0"
specs-derive = "0.4.1"
